# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-04 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(max_length=16, unique=True)),
                ('article_id', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=1)),
            ],
        ),
    ]
