# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-05 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_article_tag2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionResponseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.DiscussionResponse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Person')),
            ],
        ),
    ]
