# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-05 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_discussionresponseresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='discussion_res_res',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.DiscussionResponseResponse'),
        ),
    ]
