# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20200707_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.IntegerField(default=0),
        ),
    ]
