# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='motto',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
