# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_person_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
