# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-10 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_article_likes_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionresponse',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
