# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-13 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='article_comment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='article_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='discussion_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='discussion_response_id',
            field=models.IntegerField(null=True),
        ),
    ]
