# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20200713_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='notice',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Person'),
        ),
    ]
