# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-13 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20200713_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='article_id',
        ),
        migrations.AddField(
            model_name='notice',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Article'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='article_comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ArticleComment'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='discussion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Discussion'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='discussion_response_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.DiscussionResponse'),
        ),
    ]
