# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-13 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20200713_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='article_comment_id',
            new_name='article_comment',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='discussion_id',
            new_name='discussion',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='discussion_response_id',
            new_name='discussion_response',
        ),
    ]
