# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20200713_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='have_read',
            field=models.IntegerField(default=0),
        ),
    ]
