# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_notice_have_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('label_1', models.CharField(default='', max_length=8, null=True)),
                ('label_2', models.CharField(default='', max_length=8, null=True)),
                ('label_3', models.CharField(default='', max_length=8, null=True)),
            ],
        ),
    ]
