# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_bloglabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_id', models.IntegerField()),
                ('label_1', models.IntegerField(default=0, null=True)),
                ('label_2', models.IntegerField(default=0, null=True)),
                ('label_3', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
