# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_discussionlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlogLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('label_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDiscussionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_id', models.IntegerField()),
                ('label_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Person')),
            ],
        ),
    ]
