# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_userbloglabel_userdiscussionlabel_userlabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionlabel',
            name='label_1',
        ),
        migrations.RemoveField(
            model_name='discussionlabel',
            name='label_2',
        ),
        migrations.RemoveField(
            model_name='discussionlabel',
            name='label_3',
        ),
        migrations.AddField(
            model_name='discussionlabel',
            name='have_label',
            field=models.BinaryField(default=0, null=True),
        ),
    ]
