# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_auto_20200722_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionlabel',
            name='have_label',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
