# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-22 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20200722_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglabel',
            name='label_1',
        ),
        migrations.RemoveField(
            model_name='bloglabel',
            name='label_2',
        ),
        migrations.RemoveField(
            model_name='bloglabel',
            name='label_3',
        ),
        migrations.AddField(
            model_name='bloglabel',
            name='have_label',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
