# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20200722_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='contents_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
