# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_discussion_contents_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='contents_num',
            new_name='comments_num',
        ),
        migrations.AddField(
            model_name='article',
            name='comments_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='hot',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='read_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
