# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20200723_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField(default=0, null=True)),
                ('reader_id', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
