# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-23 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_readarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hot',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
