# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-23 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_person_fans_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='last_comment_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
