# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-30 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_auto_20200724_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='chatcontent',
            name='message_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ChatRoom'),
        ),
    ]
