# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-31 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_chatcontent_have_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='unread_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
