# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-31 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_chatroom_unread_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='unread_num',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='receiver_unread_num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='sender_unread_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
