# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-01 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_auto_20200731_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collects_num',
            field=models.IntegerField(default=0),
        ),
    ]
